### ISSUE TITLE
Playstation-gamers have lags

### ISSUE THREAD

**Issue by Leahcimkrob** [GeyserMC/GlobalLinkServer#6]
It often resets a few blocks and chests take forever to open. 
I have added a Samle-Vid, Dump-Link, and Logs from Server and Bungee
Vid: https://youtu.be/p6ptuAYn2_k
Dump: https://dump.geysermc.org/RY1SJeqgNcKAYIEUXcddzI5qpo7Shsxo
[bungee.log](https://github.com/GeyserMC/GlobalLinkServer/files/9966287/bungee.log)
[2022-11-08-2.log](https://github.com/GeyserMC/GlobalLinkServer/files/9966291/2022-11-08-2.log)

**Comment by Tim203** [comment]
You opened this issue in the GlobalLinkServer repo. Please open an issue in the Geyser repo: https://github.com/GeyserMC/Geyser/issues/new/choose
